# NumPy Practice Notebook

## The Basics

In [1]:
import numpy as np
import sys

In [28]:
a = np.array([1,2,3], dtype='int8' )
a

array([1, 2, 3], dtype=int8)

In [29]:
b = np.array([[6.0,3.0,2.0],[3.0,4.0,2.0]])
b

array([[6., 3., 2.],
       [3., 4., 2.]])

In [30]:
# get dimensions
a.ndim


1

In [31]:
#get shape 
b.shape

(2, 3)

In [32]:
# get type 
a.dtype

dtype('int8')

In [37]:
#get size 
print(a.itemsize)
print(b.itemsize)

1
8


In [34]:
#Get total size 
a.size * a.itemsize

3

or, like this:

In [35]:
#total size other method 
a.nbytes

3

## Accesing/Changing specific elements, rows, columns, etc

In [42]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [43]:
# Get a specific element [r,c]
a[1,5]

13

In [44]:
# Get a specific row

a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [45]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [46]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [52]:
#Replaces values
a[1,5] = 20
print(a)
a[:,2] = [1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [53]:
# 3D EXAMPLE
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [71]:
# Get specific element (work outside in)
print(b[0,1,0])
print(b[1,:,1])

3
[6 8]


In [73]:
# replace elements 
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## Initializing Different Types of Arrays

In [79]:
# ALL 0s MATRIX
np.zeros((2,3,4),)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [81]:
# ALL 1s MATRIX 
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [83]:
# Any other number matrix 
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [84]:
# Any other number (full_like)

In [87]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [97]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.88790369, 0.96928825],
       [0.21260217, 0.78309445],
       [0.55265419, 0.46406937],
       [0.31614305, 0.84615181]])

In [95]:
# random_sample
np.random.random_sample(a.shape)

array([[0.78665938, 0.55022838, 0.37834754, 0.27620786, 0.29299759,
        0.27440672, 0.54336886],
       [0.0972385 , 0.26637929, 0.96228909, 0.54259549, 0.4436618 ,
        0.55095671, 0.26605934]])

In [112]:
# Random Integer Values 
np.random.randint(0,100,size=(3,3))

array([[68,  2, 80],
       [52, 64, 87],
       [ 7, 11,  8]])

In [113]:
# The identity matrix 
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [122]:
# Repeat an array
arr = np.array([[1,2,3]])
print(arr)
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [135]:
x = np.ones((5,5),dtype='int8')
x[1:4,1:4] = 0
x[2,2] = 9
print(x)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


##### Be careful when copying arrays!!!


In [5]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


## Mathematics

In [6]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [7]:
a + 2

array([3, 4, 5, 6])

In [8]:
a - 2

array([-1,  0,  1,  2])

In [9]:
a * 2 

array([2, 4, 6, 8])

In [10]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [13]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [14]:
a ** 2

array([ 1,  4,  9, 16])

In [15]:
# Take the sine of all values 
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

##### Linear Algebra

In [25]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [2]:
a = np.array([[2,3],[4,5],[6,7]])
b = np.array([[2,2,2],[1,1,1]])
print(a)
print(b)
np.matmul(a,b)

[[2 3]
 [4 5]
 [6 7]]
[[2 2 2]
 [1 1 1]]


array([[ 7,  7,  7],
       [13, 13, 13],
       [19, 19, 19]])